### ISSUE TITLE
A few things

### ISSUE THREAD

**Issue by DanL12186** [learn-co-curriculum/apis-and-faraday-reading#11]
None of these things are a big deal, and I'm unsure if this is because of the version of Rails I ran this lab on (4.2.8 with Ruby 2.4.1), because the FourSquare API has been updated, or perhaps because code in the walkthrough itself was changed without changing other parts of the lab, but my experience was pretty different from what I was reading.

The first time I tried navigating to /search, after entering the supplied code, I got an unsurprising "noMethod error "body" for nilClass", as the page automatically tried to load @resp before it was instantiated. A simple .try(:body) fixed this (I'm sure if @resp/unless !@resp/if !!@resp would have too), but it was a little strange for the supplied code not to work.

Next, after continuing on and entering more code, the lesson tells us to "try entering no zipcode at all." and says "Ooph. That's ugly."

I'm assuming this is supposed to mean that you're seeing a bunch of errors or a bad request response, but no such error actually occurs, presumably because it's handled by the supplied code "if @venue", which, if it never gets any data, won't be rendered. There weren't errors in the rails server (terminal), either. 

It might also be worth noting that because this is using FourSquare's "near" attribute, that entering "Shanghai" or "Boston" in our search box works just as well as entering a Zipcode.

Lastly, the timeout bit was confusing. I expected to see "There was an error. Please try again." the way @errors had previously been populated with @error = body["meta"]["errorDetail"], but all I got was a Rails error (Net::OpenTimeout). I tried to get it to display rather than crash but couldn't make it work. 

My controller code by the end was: 

`class SearchesController < ApplicationController

  def foursquare
    begin
      @response = Faraday.get 'https://api.foursquare.com/v2/venues/search' do |req|
        req.params['client_id'] = ENV["CLIENT_ID"]
        req.params['client_secret'] = ENV["CLIENT_SECRET"]
        req.params['v'] = '20170601'
        req.params['near'] = params[:zipcode]
        req.params['query'] = 'coffee shop'
        req.options.timeout = 0
      end

      body = JSON.parse(@response.body)
      if @response.success?
        @venues = body["response"]["venues"]
      else
        @error = body["meta"]["errorDetail"]
      end

    rescue Faraday::TimeoutError
      @error = "There was a timeout. Please try again."
    end
    render 'search'
  end
end`

**Comment by gj** [comment]
Thanks for the detailed feedback @DanL12186 !

The `@resp` issue was fixed in #4, and the error handling was updated in #12. I'll leave this issue open until we have time to get to the other suggestions. Thanks again!

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
