### ISSUE TITLE
Reminder to delete Client ID/Secret

### ISSUE THREAD

**Issue by KatieLars** [learn-co-curriculum/apis-and-faraday-reading#13]
A reminder on this Readme and the Basic API lab to delete your Client ID and Client Secret would be good! Just a suggestion

**Comment by joshuaneedham** [comment]
Yes this would be a good suggestion and personally an afterthought at this point. Please update the Lab to include in BOLD remove API id info.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙

**Comment by joshuaneedham** [comment]
Perfect!
