### ISSUE TITLE
Need to add to search.html.erb, not just look at it

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/apis-and-faraday-reading#15]
The lesson says this:
"And in our template, let's take a look at that response body." I went and looked at it, but there is no mention in the lesson that you need to add this to the bottom of it:
<div>
  <%= @resp.body if @resp %>
</div>

As such, I didn't see any JSON at first, as the lesson said I would.

Thank you.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
