### ISSUE TITLE
Instructions to make sure that client_id and client_secret are Strings

### ISSUE THREAD

**Issue by aburk3** [learn-co-curriculum/apis-and-faraday-reading#16]
I tried for a while using my client_id and client_secret, but kept getting an "uninitialized constant SearchesController" error. Right before giving up and going to the next lesson I went to browse the current issues. Saw where a user had been using `ENV['client_id']` - I tried that, it didn't work, but it gave me an invalid credentials error instead of uninitialized constant. I removed the `ENV` and left the quotes, and it worked.

**Comment by catherinism** [comment]
Thank you so much for posting this issue, it really helped me! Hopefully this gets fixed soon.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
