### ISSUE TITLE
Gem Dependency Issues

### ISSUE THREAD

**Issue by sachinm78** [learn-co-curriculum/apis-and-faraday-reading#17]
I wasn't able to run Rails server to follow along with this lab in the Learn IDE.  The Gemfile might need an update.  Here is the error I got when running 'bundle install.'

`An error occurred while installing json (1.8.3), and Bundler cannot
continue.
Make sure that `gem install json -v '1.8.3' --source 'https://rubygems.org/'`
succeeds before bundling.`

**Comment by jhharwood88** [comment]
Same issue here on local client, running Ubuntu 18.10, RVM 1.29.8 (running 2.6.3) and a native ruby install of ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux].

// ♥ bundle install
Fetching gem metadata from https://rubygems.org/.............
rails (4.2.5) has dependency bundler (>= 1.3.0, < 2.0), which is unsatisfied by the current bundler version 2.0.1, so the dependency is being ignored
Using rake 10.5.0
Using i18n 0.7.0
Fetching json 1.8.3
Installing json 1.8.3 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/home/jon-laptop/.rvm/gems/ruby-2.6.3/gems/json-1.8.3/ext/json/ext/generator
/usr/share/rvm/rubies/ruby-2.6.3/bin/ruby -I
/usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0 -r
./siteconf20190627-929-jdn03v.rb extconf.rb
creating Makefile

current directory:
/home/jon-laptop/.rvm/gems/ruby-2.6.3/gems/json-1.8.3/ext/json/ext/generator
make "DESTDIR=" clean

current directory:
/home/jon-laptop/.rvm/gems/ruby-2.6.3/gems/json-1.8.3/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
generator.c: In function ‘generate_json’:
generator.c:861:25: error: ‘rb_cFixnum’ undeclared (first use in this function);
did you mean ‘mFixnum’?
     } else if (klass == rb_cFixnum) {
                         ^~~~~~~~~~
                         mFixnum
generator.c:861:25: note: each undeclared identifier is reported only once for
each function it appears in
generator.c:863:25: error: ‘rb_cBignum’ undeclared (first use in this function);
did you mean ‘mBignum’?
     } else if (klass == rb_cBignum) {
                         ^~~~~~~~~~
                         mBignum
generator.c: At top level:
cc1: warning: unrecognized command line option ‘-Wno-self-assign’
cc1: warning: unrecognized command line option ‘-Wno-parentheses-equality’
cc1: warning: unrecognized command line option ‘-Wno-constant-logical-operand’
make: *** [Makefile:244: generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in
/home/jon-laptop/.rvm/gems/ruby-2.6.3/gems/json-1.8.3 for inspection.
Results logged to
/home/jon-laptop/.rvm/gems/ruby-2.6.3/extensions/x86_64-linux/2.6.0/json-1.8.3/gem_make.out

An error occurred while installing json (1.8.3), and Bundler cannot
continue.
Make sure that `gem install json -v '1.8.3' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  rails was resolved to 4.2.5, which depends on
    actionmailer was resolved to 4.2.5, which depends on
      actionpack was resolved to 4.2.5, which depends on
        actionview was resolved to 4.2.5, which depends on
          rails-dom-testing was resolved to 1.0.7, which depends on
            rails-deprecated_sanitizer was resolved to 1.0.3, which depends on
              activesupport was resolved to 4.2.5, which depends on
                json

**Comment by DakotaLMartinez** [comment]
@sachinm78 @jhharwood88 Just in case either of you still have this issue, you can get around it by removing '4.2.5' from the rails gem in the Gemfile, removing the Gemfile.lock and running bundle install again

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
