### ISSUE TITLE
API Secrets

### ISSUE THREAD

**Issue by Eearslya** [learn-co-curriculum/apis-and-faraday-reading#9]
This lab instructs the students to go out and register their application with FourSquare to get their Client ID and **secret** key..but makes no mention at all about the fact that you should never commit a secret to a repository.

Anyone who follows this lab is going to end up pushing their FourSquare API secret up to their GitHub. There should be an additional section detailing the hazards and how to avoid them.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
